version: '3.7'

services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: '/data/postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - default
  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    command: redis-server --save 20 1 --loglevel warning

    ports:
      - 6379:6379

    volumes:
      - redis:/data/
    networks:
      - default
  mongodb:
    container_name: mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/
    networks:
      - default
networks:
  default:
    driver: bridge

volumes:
  postgres:
  redis:
  mongodb:


